---
name: build
on: [deployment, push]

jobs:
  salt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install SaltStack
        run: |
          sudo python3 -m pip install salt
          sudo salt-master -d

